# Generated by Django 3.1 on 2021-09-18 15:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='postal_address',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Почтовый адрес'),
        ),
    ]
