# Generated by Django 3.1 on 2021-09-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='home_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='home.homepage', verbose_name='Страница (привязка)'),
            preserve_default=False,
        ),
    ]
